/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example;

import org.example.entities.User;

public class App {


    public static void main(String[] args) {

        User user1=new User();
        user1.setName("ankit ojha");
        System.out.println(user1.getName());

    }
}
